version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio_test
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: miniominio
    command: server /data
    ports:
      - "9001:9000"  # Utilisation d'un port différent pour éviter les conflits
    volumes:
      - minio_test_data:/data

volumes:
  minio_test_data:
