version: '4.0'

services:
  go-server:
    container_name: go-server
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - buckets-data:/buckets
    depends_on:
    - db
    environment:
      DB_HOST: db
      DB_USER: s3user
      DB_PASSWORD: s3password
      DB_NAME: s3db
      BUCKET_PATH: /buckets

  db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: s3db
      POSTGRES_USER: s3user
      POSTGRES_PASSWORD: s3password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  buckets-data: