version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_${GO_ENV}
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data # Utilisation d'un nom statique ici

  goland:
    image: golang:1.20
    container_name: goland_${GO_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "${GO_PORT}:${GO_PORT}"
    depends_on:
      - minio
    environment:
      - GO_ENV=${GO_ENV}

volumes:
  minio_data: # Nom de volume statique
